Fix #5722 Make SearchForm2.php customizable
salesagility/SuiteCRM pull request #10089
Opened 2023-06-13 10:41 UTC by pgorod

## Description
Fixes #5722 making SearchForm2.php customizable

## How To Test This
See Issue

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2023-06-19 14:31 UTC, serhiisamko091184 commented
Hello @pgorod ,
thanks for your contribution! 

Regards, 
Serhii

2023-09-08 14:18 UTC, clemente-raposo approved these changes

2023-10-12 14:55 UTC, clemente-raposo commented
Hi @pgorod, question on this PR. 

A developer still needs to extend the `view.list.php` in order to extend the SearchForm2. 

The class name won't be the same so even if you have SearchForm2Custom on your custom file, it won't be picked up

2023-10-13 09:05 UTC, pgorod commented
I guess this is good only for a pretty dumb way of customizing - it's just a brute-force replacement of a 1500-lines file. It works for some cases. I guess it's still better than having to touch a bunch of core files just to customize search behaviour.

If you want to merge it like this, even though it's not the best design, I suppose it won't hurt, since this older v7 code is on it's way to being replaced by v8, any way. But if you prefer to close without merging, I don't object.

2025-03-28 16:08 UTC, johnM2401 requested changes
Hey!
Thank you for this PR

I've given this a test locally and while this PR *does* allow custom SearchForm files, it looks like the CRM returns a FATAL if the user does *not* have a custom SearchForm and SearchForm2.
(ie: OOTB state)

See gif:
 ![custSearchFormFatal](https://github.com/user-attachments/assets/220e8082-af68-4dcb-805d-c0f72e8173c1)


Thanks!

2025-03-28 16:26 UTC, pgorod commented
Hi John!

Isn't that just a transient error? Does it stay the same even after a hard-refresh, or after a QR&R?

Can you please also get me the text of the FATAL from the logs? Thanks

2025-03-28 17:39 UTC, johnM2401 commented
Hey @pgorod !

The FATAL was:

```
[28-Mar-2025 16:04:21 UTC] PHP Fatal error:  Uncaught Error: Class "SearchForm\SearchForm" not found in /var/www/suitecrm_git/include/MVC/View/views/view.list.php:327
Stack trace:
#0 /var/www/suitecrm_git/include/MVC/View/views/view.list.php(256): ViewList->prepareSearchForm()
#1 /var/www/suitecrm_git/include/MVC/View/views/view.list.php(392): ViewList->listViewPrepare()
#2 /var/www/suitecrm_git/include/MVC/View/SugarView.php(210): ViewList->display()
#3 /var/www/suitecrm_git/include/MVC/Controller/SugarController.php(432): SugarView->process()
#4 /var/www/suitecrm_git/include/MVC/Controller/SugarController.php(363): SugarController->processView()
#5 /var/www/suitecrm_git/include/MVC/SugarApplication.php(101): SugarController->execute()
#6 /var/www/suitecrm_git/index.php(52): SugarApplication->execute()
#7 {main}
  thrown in /var/www/suitecrm_git/include/MVC/View/views/view.list.php on line 327

```

<br>

I believe I had run QR&R / Perms / Hard Reload, but I will run through this again to be totally sure and will let you know how it goes.
(And I'll try to get some more concrete steps to replicate for you)

<br>

Thanks again!

2025-03-28 18:10 UTC, pgorod commented
The reason I am skeptical is that (supposedly) this code runs exactly the same as before in the cases where there is no custom file present...

```php
function get_custom_file_if_exists($file)
{
    return file_exists("custom/{$file}") ? "custom/{$file}" : $file;
}
```

2025-03-31 11:30 UTC, johnM2401 commented
Hey @pgorod !
Thank you for your time on this.

I've merged this back in locally and I'm no longer seeing the issue above.
But, curiously, I'm getting the inverse now...

<br>

It looks to FATAL out when there *is* a custom SearchForm/SearchForm2 file found.

It's returning the error:
```
[31-Mar-2025 11:19:58 UTC] PHP Fatal error:  Cannot declare class SearchForm, because the name is already in use in /var/www/suitecrm_git/include/SearchForm/SearchForm2.php on line 51
```

Which seems to drill down to Line 251 calling the Original SearchForm2 at: ```include/ListView/ListViewData.php```
![image](https://github.com/user-attachments/assets/ed170d9e-5fcf-40c2-aabe-19dcad2ae4a0)

Changing this to ```require_once(get_custom_file_if_exists('include/SearchForm/SearchForm2.php'));``` seems to resolve the issue and allow me to use a Custom Searchform2, but I'm not sure if this change would have any unexpected effects on Listview behaviour elsewhere.

<br>

Is this anything you've come across when using/developing this?

Thank you again!

2025-04-01 11:17 UTC, pgorod commented
I think it's ok to do that additional change

`require_once(get_custom_file_if_exists('include/SearchForm/SearchForm2.php'));`

none of this is very good design but it still does allow for some solutions, and it won't hurt. Only people adding custom files will see any effect. 👍 

I am having technical difficulties at this time, I don't have a functional IDE/git so if you can please make the changes yourself I would appreciate it. Or just close this and start a new PR (this one would need some fixes to the commits, that I can't do here from the online Github). Thanks

2026-02-27 17:37 UTC, merged