Deprecate AOD (Lucene)
salesagility/SuiteCRM pull request #9094
Opened 2021-04-15 17:04 UTC by Dillon-Brown

## Description

- Deprecated ```AOD_Index``` and ```AOD_IndexEvent``` modules.
- Added a deprecation log that will trigger only on an index event (To avoid log spam).
- Deprecated ```PdfParser```, this is only used in one place by ```AOD_Index``` and there are other options to parse PDFs in core.

## How To Test This

1. Enable AOD
2. Check that the index event logs a deprecation notice.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2021-04-15 17:52 UTC, mattlorimer requested changes
By 12.0.0 I assume you meant 7.12.0?

2021-04-15 18:17 UTC, Dillon-Brown commented
> By 12.0.0 I assume you meant 7.12.0?

🤦‍♂️ Yup exactly.... Pushed :D.

2021-04-19 14:19 UTC, clemente-raposo approved these changes

2021-04-19 14:21 UTC, mattlorimer approved these changes

2021-04-23 08:06 UTC, merged