Fix #5814 Email template date handling
salesagility/SuiteCRM pull request #9392
Opened 2021-12-08 10:58 UTC by clemente-raposo

## Description

- Fix issue: https://github.com/salesagility/SuiteCRM/issues/5814
    - Apply user formatting to date and datetime on pdf templates 

## Motivation and Context

- Fix issue: https://github.com/salesagility/SuiteCRM/issues/5814
    - Apply user formatting to date and datetime on pdf templates 

## How To Test This

- See steps to reproduce in:  https://github.com/salesagility/SuiteCRM/issues/5814

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

2022-01-24 14:26 UTC, jack7anderson7 submitted a review, later dismissed

2022-01-25 12:27 UTC, mattlorimer requested changes

2022-01-25 12:27 UTC, mattlorimer commented on modules/AOS_PDF_Templates/templateParser.php
> +                        $dateValue = self::getDateFormatService()->toUserDate($dateValue);
we probably need to take account of the system format or a specific template format as opposed to the users format, it may not make sense

2022-02-09 09:52 UTC, clemente-raposo commented on include/language/en_us.lang.php
> +$app_list_strings['template_date_format'][''] = '';
Hi @jack7anderson7,

We should probably initialized this entry with something like `$app_list_strings['template_date_format'] = []`

2022-02-09 09:54 UTC, clemente-raposo commented on modules/AOP_Case_Updates/util.php
> +function aop_parse_template($string, $bean_arr, $template)
Hi @jack7anderson7,

We should update the comments and add a new `@param`

2022-02-09 09:57 UTC, clemente-raposo commented on modules/AOS_PDF_Templates/templateParser.php
> +                    $templateFormat = $template->template_date_format ?? '';
Hi @jack7anderson7,

We have a duplicate `templateFormat = $template->template_date_format ?? '';`

2022-02-09 09:58 UTC, clemente-raposo commented on modules/AOW_Actions/actions/actionSendEmail.php
> +    public function run_action(SugarBean $bean, $params = array(), $in_save = false, $template): bool
Hi @jack7anderson7,

Why are we adding `$template` as an argument here?

2022-02-09 10:03 UTC, clemente-raposo commented on modules/AOS_PDF_Templates/generatePdf.php
> +function populate_service_lines($text, $lineItems, $element = 'tr', $template)
Hi @jack7anderson7,

We are adding this argument here, but we don't change the place that calls this method.

2022-02-09 10:04 UTC, clemente-raposo commented on modules/AOS_PDF_Templates/generatePdf.php
> +function populate_product_lines($text, $lineItems, $element = 'tr', $template)
Hi @jack7anderson7,

We are adding this argument here, but we don't change the place that calls this method.

2022-02-09 10:59 UTC, clemente-raposo commented on modules/AOW_Actions/actions/actionSendEmail.php
> +    public function run_action(SugarBean $bean, $params = array(), $in_save = false, $template): bool
@jack7anderson7 we should remove the `$template` here and in all `run_action`

2024-03-18 10:35 UTC, serhiisamko091184 commented
Hello, @clemente-raposo 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

2024-05-01 14:42 UTC, serhiisamko091184 commented
Hey @clemente-raposo 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

2024-05-01 14:42 UTC, closed without merging